#[[main]]
#  name = "Projects"
#  pageRef = "projects"
#  weight = 10

[[main]]
  name = "Reference"
  pageRef = "reference"
  weight = 20

#[[main]]
#  name = "Contact"
#  pageRef = "contact"
#  weight = 30