# [[main]]
#  name = "Projects"
#  pageRef = "projects"
#  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 15

[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 20

# [[main]]
#  name = "Contact"
#  pageRef = "contact"
#  weight = 30